### ISSUE TITLE
How to use the "timeago" library ?

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#11]
I installed the library in the folder `/libraries` from my site.

I created an empty `timeago.js` file in :

`/public_html/web/themes/contrib/bootstrap_subtheme_front_office/js`

and I modified `bootstrap_subtheme_front_office.libraries.yml` like this :

```
framework:
  css:
    theme:
      fonts/font-awesome/web-fonts-with-css/css/fontawesome-all.css: {}
#      bootstrap/dist/css/bootstrap.css: {}
#      css/bootstrap-cosmo.css: {}
      css/style.css: {}
#      css/style-noel.css: {}
#      css/style-nouvel-an.css: {}
  js:
    bootstrap/js/affix.js: {}
    bootstrap/js/alert.js: {}
    bootstrap/js/button.js: {}
    bootstrap/js/carousel.js: {}
    bootstrap/js/collapse.js: {}
#    bootstrap/js/dropdown.js: {}
    bootstrap/js/modal.js: {}
    bootstrap/js/tooltip.js: {}
    bootstrap/js/popover.js: {}
    bootstrap/js/scrollspy.js: {}
    bootstrap/js/tab.js: {}
    bootstrap/js/transition.js: {}
#    js/tour.js: {}
    js/collapse.js: {}
    js/timeago.js: {}
```

What is the complete code to put in `timeago.js` ?
